replicaCount: 1

image:
  repository: hughestris/docker-pipeline-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: bookstore.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  DATABASE_URL: sqlite:///./db/books.db
  LOG_LEVEL: INFO
  LOG_FORMAT: '%(levelname)s:%(name)s:%(message)s'
  PAGE_SIZE: "10"
  APP_ENV: dev
  HOST: 0.0.0.0
  PORT: "8080"
  RELOAD: "False"
  ALLOWED_ORIGINS: "*"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
