apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookstore-api.fullname" . }}-config
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  LOG_FORMAT: {{ .Values.env.LOG_FORMAT | quote }}
  PAGE_SIZE: {{ .Values.env.PAGE_SIZE | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  HOST: {{ .Values.env.HOST | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  RELOAD: {{ .Values.env.RELOAD | quote }}
  ALLOWED_ORIGINS: {{ .Values.env.ALLOWED_ORIGINS | quote }}
  DB_POOL_SIZE: {{ .Values.env.DB_POOL_SIZE | quote }}
  DB_MAX_OVERFLOW: {{ .Values.env.DB_MAX_OVERFLOW | quote }}
