name: Build, Push & Helm Package

on:
  push:
    branches:
      - main  # or your testing branch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t docker-pipeline-demo:latest .
          docker tag docker-pipeline-demo:latest ${{ secrets.DOCKER_USERNAME }}/docker-pipeline-demo:latest

      - name: Push the image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-pipeline-demo:latest
