name: Build, Push & Helm Package

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: docker-pipeline-demo
  CHART_DIR: bookstore-api-chart

jobs:
  build-push-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          helm lint $CHART_DIR
          helm package $CHART_DIR --destination packaged

      - name: Upload Helm Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookstore-api-chart
          path: packaged/bookstore-api-*.tgz
